//=====================================================
// This file was auto-generated by xlate_vreg v1.3
//            -->  DO NOT EDIT!  <-- 
//=====================================================
#ifndef _FPGA_REG_H
#define _FPGA_REG_H


//
// Register:    REG_USE_SIM_DATA
// Size:        32-bits
// Type:        Read/Write
// Description: Set this to 1 to use simulated host-RAM data
//              Set this to 0 to use real data from host-RAM
//
#define REG_USE_SIM_DATA                                             0x0000000000001000ULL


//
// Register:    REG_HOST_FRAME_SIZE
// Size:        32-bits
// Type:        Read/Write
// Description: The size of a frame in host-RAM.
//
#define REG_HOST_FRAME_SIZE                                          0x0000000000001004ULL


//
// Register:    REG_FD_HOST_ADDR
// Size:        64-bits
// Type:        Read/Write
// Description: The base address of frame data in host-RAM.
//              Must be on a 4KB boundary
//
#define REG_FD_HOST_ADDR                                             0x4000000000001008ULL


//
// Register:    REG_FD_HOST_SIZE
// Size:        64-bits
// Type:        Read/Write
// Description: The size of the frame-data ring-buffer in host-RAM.
//              Must be a multiple of 8KB
//
#define REG_FD_HOST_SIZE                                             0x4000000000001010ULL


//
// Register:    REG_UW_HOST_ADDR
// Size:        64-bits
// Type:        Read/Write
// Description: The base address where userwave-data will be stored in host-RAM
//              Must be on a 4KB boundary
//
#define REG_UW_HOST_ADDR                                             0x4000000000001018ULL


//
// Register:    REG_UW_HOST_SIZE
// Size:        64-bits
// Type:        Read/Write
// Description: The size of the ring-buffer where userwave-data will be stored
//              in host-RAM.   Must be a multiple of 4KB
//
#define REG_UW_HOST_SIZE                                             0x4000000000001020ULL


//
// Register:    REG_FRM_CONSUMED
// Size:        64-bits
// Type:        Read/Write
// Description: The number of frames of data consumed so far
//
#define REG_FRM_CONSUMED                                             0x4000000000001028ULL


//
// Register:    REG_UW_WRITTEN_H
// Size:        32-bits
// Type:        Read/Write
// Description: The number of 4KB blocks of userwave-data written
//              to host-RAM.
//
#define REG_UW_WRITTEN_H                                             0x0000000000001030ULL


//
// Register:    REG_START
// Size:        32-bits
// Type:        Read/Write
// Description: Write a 1 to this register to pre-fill the outgoing
//              FIFOs with data from host-RAM
//              This is cleared to zero by a reset
//
#define REG_START                                                    0x0000000000001038ULL


//
// Register:    REG_READY
// Size:        32-bits
// Type:        Read only
// Description: When this is non-zero, the system is ready to receive packet requests
//              After writing a 1 to REG_START, wait for REG_READY to be non-zero
//
#define REG_READY                                                    0x000000000000103cULL


//
// Register:    REG_RESET
// Size:        32-bits
// Type:        Read/Write
// Description: Write a 1 to this register to reset the system
//              Auto-clears to 0 when the reset operation is complete
//
#define REG_RESET                                                    0x0000000000001040ULL


//
// Register:    REG_SEND
// Size:        32-bits
// Type:        Read/Write
// Description: Write a value to this register to send that
//              number of packet-pairs
//              >>>>  FOR DEBUGGING ONLY <<<<
//
#define REG_SEND                                                     0x0000000000001044ULL


//
// Register:    REG_HBM0_TEMP
// Size:        32-bits
// Type:        Read only
// Description: The temperature in degrees C of HBM Bank 0
//
#define REG_HBM0_TEMP                                                0x0000000000001048ULL


//
// Register:    REG_HBM1_TEMP
// Size:        32-bits
// Type:        Read only
// Description: The temperature in degrees C of HBM Bank 1
//
#define REG_HBM1_TEMP                                                0x000000000000104cULL


//
// Register:    REG_SELFTEST_ERR
// Size:        32-bits
// Type:        Read only
// Description: Indicates a FIFO self-test failed
//              Bit 0 = 1 = Channel 0 self-test failed
//              Bit 1 = 1 = Channel 1 self-test failed
//
#define REG_SELFTEST_ERR                                             0x0000000000001050ULL



#endif
